Class Formation.Msg.FormationInsertAllRequest Extends Ens.Request
{

Property ListOfAllObjFormation As list Of Formation.Obj.Formation;

Storage Default
{
<Data name="FormationInsertAllRequestDefaultData">
<Subscript>"FormationInsertAllRequest"</Subscript>
<Value name="1">
<Value>ListOfAllObjFormation</Value>
</Value>
</Data>
<DefaultData>FormationInsertAllRequestDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
